### ISSUE TITLE
"Countdown Sprint" showing half of actual remaining days when all setting are set

### ISSUE THREAD

**Issue by DanBirchgrove** [ALM-Rangers/Countdown-Widget-Extension#46] opened 2018-10-25 08:53 UTC
Given an iteration setup starting at 2018-10-01 and ending at 2018-12-31 
And "Skip non-working days" is set
When "Change background color when less than specified numbers of hours" is set
Then the number of days shown on the widget is exactly half of number of days when "Skip non-working days" is not set.

**Exempel:**
Today is 2018-10-25. 

Given "Change background color when less than specified numbers of hours" is set
When "Skip non-working days" is **not** set 
Then the number of days remaining is shown as 68.

Given "Change background color when less than specified numbers of hours" is set
When "Skip non-working days" is set 
Then the number of days remaining is shown as 34.

![image](https://user-images.githubusercontent.com/40863251/47487975-c8ea3200-d843-11e8-8ad6-46e069990bcd.png)

![image](https://user-images.githubusercontent.com/40863251/47488035-e3241000-d843-11e8-80ad-e7a56ec62684.png)

**Comment by henrybeen** [comment] 2018-10-29 07:10
Thanks for reporting this issue.

I have reproduced the issue and it is due to an get.. method having side-effects. For this reason running the calculations again for changing the background color (or not), will subtract non-working days twice.

I will check a fix in shortly and then it will be released along with other changes.

**Closed** 2018-10-31 06:37 UTC
